apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-monolothic-example-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-monolothic-example
  template:
    metadata:
      labels:
        app: java-monolothic-example
    spec:
      containers:
        - name: java-monolothic-example-container
          image: tycinar42/javamonolithicexample:v001
          ports:
            - containerPort: 9090