apiVersion: v1
kind: Service
metadata:
  name: one-loadbalancer
spec:
  type: LoadBalancer
  selector:
    service: commentservice
  ports:
    - port: 9092
      targetPort: 9090
      name: tcpcommentapp
    - port: 3333
      targetPort: 5432
      name: tcppostgre