apiVersion: v1
kind: Secret
metadata:
  name: commentapp-secret
type: Opaque
stringData:
  DBURL: "jdbc:postgresql://35.226.238.223:1515/commentAppDb"
  DBUSER: "postgres"
  DBPASSWORD: "root"
  SERVER_PORT: "9090"