apiVersion: v1
kind: Service
metadata:
  name: microservice-assignment-service
spec:
  type: LoadBalancer
  selector:
    app: microservice-assignment
  ports:
    - port: 9090
      targetPort: 9090
  