apiVersion: v1
kind: Pod
metadata:
  name:  helloworld
  labels:
    type: back-end
    app: user-service
spec:
  containers:
  - image:  musty1406/helloworldapp:v001
    name:  helloworld
    ports:
      - containerPort: 9090
    env:
      - name: SERVERPORT
        value: "9090"