apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      database: postgresql
  template:
    metadata:
      labels:
        database: postgresql
    spec:
      containers:
        - name: postgresql-container
          image: postgres:latest
          resources:
            requests:
              memory: "1024Mi"
              cpu: "0.1"
            limits:
              memory: "4096Mi"
              cpu: "0.25"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-myproject
                  key: DBPASS

    