apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    team: helloapp-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloapp 
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
      - image: musty1406/helloworldapp:v003
        name: hellopod
        ports:
          - containerPort: 8090  