apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      database: postgresql
  template:
    metadata:
      labels:
        database: postgresql
    spec:
      containers:
        - name: postgre-container
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "root"
