apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  DBURL: "jdbc:postgresql://10.88.0.38:5432/commentAppDb"
  DBUSER: "postgres"
  DBPASSWORD: "root"
  SERVER_PORT: "9090"
